package com.coc.character.pojo.req;

public class SkillReq {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.userid
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.hp
     *
     * @mbg.generated
     */
    private Integer hp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.mp
     *
     * @mbg.generated
     */
    private Integer mp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.potential
     *
     * @mbg.generated
     */
    private Integer potential;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.interest
     *
     * @mbg.generated
     */
    private Integer interest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.shin
     *
     * @mbg.generated
     */
    private Integer shin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.swim
     *
     * @mbg.generated
     */
    private Integer swim;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.spy
     *
     * @mbg.generated
     */
    private Integer spy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.listen
     *
     * @mbg.generated
     */
    private Integer listen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.libaray
     *
     * @mbg.generated
     */
    private Integer libaray;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.negotiate
     *
     * @mbg.generated
     */
    private Integer negotiate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.occultism
     *
     * @mbg.generated
     */
    private Integer occultism;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.cthulhu
     *
     * @mbg.generated
     */
    private Integer cthulhu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.drive
     *
     * @mbg.generated
     */
    private Integer drive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.combat
     *
     * @mbg.generated
     */
    private Integer combat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.gun
     *
     * @mbg.generated
     */
    private Integer gun;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.san
     *
     * @mbg.generated
     */
    private Integer san;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.currenthp
     *
     * @mbg.generated
     */
    private Integer currenthp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.currentmp
     *
     * @mbg.generated
     */
    private Integer currentmp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.currentsan
     *
     * @mbg.generated
     */
    private Integer currentsan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.profession
     *
     * @mbg.generated
     */
    private String profession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.accountant
     *
     * @mbg.generated
     */
    private Integer accountant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.anthropology
     *
     * @mbg.generated
     */
    private Integer anthropology;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.evaluate
     *
     * @mbg.generated
     */
    private Integer evaluate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.archeology
     *
     * @mbg.generated
     */
    private Integer archeology;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.charm
     *
     * @mbg.generated
     */
    private Integer charm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.computer
     *
     * @mbg.generated
     */
    private Integer computer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.credit
     *
     * @mbg.generated
     */
    private Integer credit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.dress
     *
     * @mbg.generated
     */
    private Integer dress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.dodge
     *
     * @mbg.generated
     */
    private Integer dodge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.electrical
     *
     * @mbg.generated
     */
    private Integer electrical;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.mechanology
     *
     * @mbg.generated
     */
    private Integer mechanology;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.law
     *
     * @mbg.generated
     */
    private Integer law;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.locksmith
     *
     * @mbg.generated
     */
    private Integer locksmith;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.sneak
     *
     * @mbg.generated
     */
    private Integer sneak;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.medical
     *
     * @mbg.generated
     */
    private Integer medical;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.foreign
     *
     * @mbg.generated
     */
    private Integer foreign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.pilot
     *
     * @mbg.generated
     */
    private Integer pilot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.psychology
     *
     * @mbg.generated
     */
    private Integer psychology;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.trace
     *
     * @mbg.generated
     */
    private Integer trace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.aid
     *
     * @mbg.generated
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.heavy
     *
     * @mbg.generated
     */
    private Integer heavy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.steal
     *
     * @mbg.generated
     */
    private Integer steal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.threaten
     *
     * @mbg.generated
     */
    private Integer threaten;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill.chemistry
     *
     * @mbg.generated
     */
    private Integer chemistry;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.userid
     *
     * @return the value of skill.userid
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.userid
     *
     * @param userid the value for skill.userid
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.hp
     *
     * @return the value of skill.hp
     *
     * @mbg.generated
     */
    public Integer getHp() {
        return hp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.hp
     *
     * @param hp the value for skill.hp
     *
     * @mbg.generated
     */
    public void setHp(Integer hp) {
        this.hp = hp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.mp
     *
     * @return the value of skill.mp
     *
     * @mbg.generated
     */
    public Integer getMp() {
        return mp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.mp
     *
     * @param mp the value for skill.mp
     *
     * @mbg.generated
     */
    public void setMp(Integer mp) {
        this.mp = mp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.name
     *
     * @return the value of skill.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.name
     *
     * @param name the value for skill.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.potential
     *
     * @return the value of skill.potential
     *
     * @mbg.generated
     */
    public Integer getPotential() {
        return potential;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.potential
     *
     * @param potential the value for skill.potential
     *
     * @mbg.generated
     */
    public void setPotential(Integer potential) {
        this.potential = potential;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.interest
     *
     * @return the value of skill.interest
     *
     * @mbg.generated
     */
    public Integer getInterest() {
        return interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.interest
     *
     * @param interest the value for skill.interest
     *
     * @mbg.generated
     */
    public void setInterest(Integer interest) {
        this.interest = interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.shin
     *
     * @return the value of skill.shin
     *
     * @mbg.generated
     */
    public Integer getShin() {
        return shin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.shin
     *
     * @param shin the value for skill.shin
     *
     * @mbg.generated
     */
    public void setShin(Integer shin) {
        this.shin = shin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.swim
     *
     * @return the value of skill.swim
     *
     * @mbg.generated
     */
    public Integer getSwim() {
        return swim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.swim
     *
     * @param swim the value for skill.swim
     *
     * @mbg.generated
     */
    public void setSwim(Integer swim) {
        this.swim = swim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.spy
     *
     * @return the value of skill.spy
     *
     * @mbg.generated
     */
    public Integer getSpy() {
        return spy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.spy
     *
     * @param spy the value for skill.spy
     *
     * @mbg.generated
     */
    public void setSpy(Integer spy) {
        this.spy = spy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.listen
     *
     * @return the value of skill.listen
     *
     * @mbg.generated
     */
    public Integer getListen() {
        return listen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.listen
     *
     * @param listen the value for skill.listen
     *
     * @mbg.generated
     */
    public void setListen(Integer listen) {
        this.listen = listen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.libaray
     *
     * @return the value of skill.libaray
     *
     * @mbg.generated
     */
    public Integer getLibaray() {
        return libaray;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.libaray
     *
     * @param libaray the value for skill.libaray
     *
     * @mbg.generated
     */
    public void setLibaray(Integer libaray) {
        this.libaray = libaray;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.negotiate
     *
     * @return the value of skill.negotiate
     *
     * @mbg.generated
     */
    public Integer getNegotiate() {
        return negotiate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.negotiate
     *
     * @param negotiate the value for skill.negotiate
     *
     * @mbg.generated
     */
    public void setNegotiate(Integer negotiate) {
        this.negotiate = negotiate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.occultism
     *
     * @return the value of skill.occultism
     *
     * @mbg.generated
     */
    public Integer getOccultism() {
        return occultism;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.occultism
     *
     * @param occultism the value for skill.occultism
     *
     * @mbg.generated
     */
    public void setOccultism(Integer occultism) {
        this.occultism = occultism;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.cthulhu
     *
     * @return the value of skill.cthulhu
     *
     * @mbg.generated
     */
    public Integer getCthulhu() {
        return cthulhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.cthulhu
     *
     * @param cthulhu the value for skill.cthulhu
     *
     * @mbg.generated
     */
    public void setCthulhu(Integer cthulhu) {
        this.cthulhu = cthulhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.drive
     *
     * @return the value of skill.drive
     *
     * @mbg.generated
     */
    public Integer getDrive() {
        return drive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.drive
     *
     * @param drive the value for skill.drive
     *
     * @mbg.generated
     */
    public void setDrive(Integer drive) {
        this.drive = drive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.combat
     *
     * @return the value of skill.combat
     *
     * @mbg.generated
     */
    public Integer getCombat() {
        return combat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.combat
     *
     * @param combat the value for skill.combat
     *
     * @mbg.generated
     */
    public void setCombat(Integer combat) {
        this.combat = combat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.gun
     *
     * @return the value of skill.gun
     *
     * @mbg.generated
     */
    public Integer getGun() {
        return gun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.gun
     *
     * @param gun the value for skill.gun
     *
     * @mbg.generated
     */
    public void setGun(Integer gun) {
        this.gun = gun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.san
     *
     * @return the value of skill.san
     *
     * @mbg.generated
     */
    public Integer getSan() {
        return san;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.san
     *
     * @param san the value for skill.san
     *
     * @mbg.generated
     */
    public void setSan(Integer san) {
        this.san = san;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.currenthp
     *
     * @return the value of skill.currenthp
     *
     * @mbg.generated
     */
    public Integer getCurrenthp() {
        return currenthp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.currenthp
     *
     * @param currenthp the value for skill.currenthp
     *
     * @mbg.generated
     */
    public void setCurrenthp(Integer currenthp) {
        this.currenthp = currenthp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.currentmp
     *
     * @return the value of skill.currentmp
     *
     * @mbg.generated
     */
    public Integer getCurrentmp() {
        return currentmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.currentmp
     *
     * @param currentmp the value for skill.currentmp
     *
     * @mbg.generated
     */
    public void setCurrentmp(Integer currentmp) {
        this.currentmp = currentmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.currentsan
     *
     * @return the value of skill.currentsan
     *
     * @mbg.generated
     */
    public Integer getCurrentsan() {
        return currentsan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.currentsan
     *
     * @param currentsan the value for skill.currentsan
     *
     * @mbg.generated
     */
    public void setCurrentsan(Integer currentsan) {
        this.currentsan = currentsan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.profession
     *
     * @return the value of skill.profession
     *
     * @mbg.generated
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.profession
     *
     * @param profession the value for skill.profession
     *
     * @mbg.generated
     */
    public void setProfession(String profession) {
        this.profession = profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.accountant
     *
     * @return the value of skill.accountant
     *
     * @mbg.generated
     */
    public Integer getAccountant() {
        return accountant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.accountant
     *
     * @param accountant the value for skill.accountant
     *
     * @mbg.generated
     */
    public void setAccountant(Integer accountant) {
        this.accountant = accountant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.anthropology
     *
     * @return the value of skill.anthropology
     *
     * @mbg.generated
     */
    public Integer getAnthropology() {
        return anthropology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.anthropology
     *
     * @param anthropology the value for skill.anthropology
     *
     * @mbg.generated
     */
    public void setAnthropology(Integer anthropology) {
        this.anthropology = anthropology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.evaluate
     *
     * @return the value of skill.evaluate
     *
     * @mbg.generated
     */
    public Integer getEvaluate() {
        return evaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.evaluate
     *
     * @param evaluate the value for skill.evaluate
     *
     * @mbg.generated
     */
    public void setEvaluate(Integer evaluate) {
        this.evaluate = evaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.archeology
     *
     * @return the value of skill.archeology
     *
     * @mbg.generated
     */
    public Integer getArcheology() {
        return archeology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.archeology
     *
     * @param archeology the value for skill.archeology
     *
     * @mbg.generated
     */
    public void setArcheology(Integer archeology) {
        this.archeology = archeology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.charm
     *
     * @return the value of skill.charm
     *
     * @mbg.generated
     */
    public Integer getCharm() {
        return charm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.charm
     *
     * @param charm the value for skill.charm
     *
     * @mbg.generated
     */
    public void setCharm(Integer charm) {
        this.charm = charm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.computer
     *
     * @return the value of skill.computer
     *
     * @mbg.generated
     */
    public Integer getComputer() {
        return computer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.computer
     *
     * @param computer the value for skill.computer
     *
     * @mbg.generated
     */
    public void setComputer(Integer computer) {
        this.computer = computer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.credit
     *
     * @return the value of skill.credit
     *
     * @mbg.generated
     */
    public Integer getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.credit
     *
     * @param credit the value for skill.credit
     *
     * @mbg.generated
     */
    public void setCredit(Integer credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.dress
     *
     * @return the value of skill.dress
     *
     * @mbg.generated
     */
    public Integer getDress() {
        return dress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.dress
     *
     * @param dress the value for skill.dress
     *
     * @mbg.generated
     */
    public void setDress(Integer dress) {
        this.dress = dress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.dodge
     *
     * @return the value of skill.dodge
     *
     * @mbg.generated
     */
    public Integer getDodge() {
        return dodge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.dodge
     *
     * @param dodge the value for skill.dodge
     *
     * @mbg.generated
     */
    public void setDodge(Integer dodge) {
        this.dodge = dodge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.electrical
     *
     * @return the value of skill.electrical
     *
     * @mbg.generated
     */
    public Integer getElectrical() {
        return electrical;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.electrical
     *
     * @param electrical the value for skill.electrical
     *
     * @mbg.generated
     */
    public void setElectrical(Integer electrical) {
        this.electrical = electrical;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.mechanology
     *
     * @return the value of skill.mechanology
     *
     * @mbg.generated
     */
    public Integer getMechanology() {
        return mechanology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.mechanology
     *
     * @param mechanology the value for skill.mechanology
     *
     * @mbg.generated
     */
    public void setMechanology(Integer mechanology) {
        this.mechanology = mechanology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.law
     *
     * @return the value of skill.law
     *
     * @mbg.generated
     */
    public Integer getLaw() {
        return law;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.law
     *
     * @param law the value for skill.law
     *
     * @mbg.generated
     */
    public void setLaw(Integer law) {
        this.law = law;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.locksmith
     *
     * @return the value of skill.locksmith
     *
     * @mbg.generated
     */
    public Integer getLocksmith() {
        return locksmith;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.locksmith
     *
     * @param locksmith the value for skill.locksmith
     *
     * @mbg.generated
     */
    public void setLocksmith(Integer locksmith) {
        this.locksmith = locksmith;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.sneak
     *
     * @return the value of skill.sneak
     *
     * @mbg.generated
     */
    public Integer getSneak() {
        return sneak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.sneak
     *
     * @param sneak the value for skill.sneak
     *
     * @mbg.generated
     */
    public void setSneak(Integer sneak) {
        this.sneak = sneak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.medical
     *
     * @return the value of skill.medical
     *
     * @mbg.generated
     */
    public Integer getMedical() {
        return medical;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.medical
     *
     * @param medical the value for skill.medical
     *
     * @mbg.generated
     */
    public void setMedical(Integer medical) {
        this.medical = medical;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.foreign
     *
     * @return the value of skill.foreign
     *
     * @mbg.generated
     */
    public Integer getForeign() {
        return foreign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.foreign
     *
     * @param foreign the value for skill.foreign
     *
     * @mbg.generated
     */
    public void setForeign(Integer foreign) {
        this.foreign = foreign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.pilot
     *
     * @return the value of skill.pilot
     *
     * @mbg.generated
     */
    public Integer getPilot() {
        return pilot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.pilot
     *
     * @param pilot the value for skill.pilot
     *
     * @mbg.generated
     */
    public void setPilot(Integer pilot) {
        this.pilot = pilot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.psychology
     *
     * @return the value of skill.psychology
     *
     * @mbg.generated
     */
    public Integer getPsychology() {
        return psychology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.psychology
     *
     * @param psychology the value for skill.psychology
     *
     * @mbg.generated
     */
    public void setPsychology(Integer psychology) {
        this.psychology = psychology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.trace
     *
     * @return the value of skill.trace
     *
     * @mbg.generated
     */
    public Integer getTrace() {
        return trace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.trace
     *
     * @param trace the value for skill.trace
     *
     * @mbg.generated
     */
    public void setTrace(Integer trace) {
        this.trace = trace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.aid
     *
     * @return the value of skill.aid
     *
     * @mbg.generated
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.aid
     *
     * @param aid the value for skill.aid
     *
     * @mbg.generated
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.heavy
     *
     * @return the value of skill.heavy
     *
     * @mbg.generated
     */
    public Integer getHeavy() {
        return heavy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.heavy
     *
     * @param heavy the value for skill.heavy
     *
     * @mbg.generated
     */
    public void setHeavy(Integer heavy) {
        this.heavy = heavy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.steal
     *
     * @return the value of skill.steal
     *
     * @mbg.generated
     */
    public Integer getSteal() {
        return steal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.steal
     *
     * @param steal the value for skill.steal
     *
     * @mbg.generated
     */
    public void setSteal(Integer steal) {
        this.steal = steal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.threaten
     *
     * @return the value of skill.threaten
     *
     * @mbg.generated
     */
    public Integer getThreaten() {
        return threaten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.threaten
     *
     * @param threaten the value for skill.threaten
     *
     * @mbg.generated
     */
    public void setThreaten(Integer threaten) {
        this.threaten = threaten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill.chemistry
     *
     * @return the value of skill.chemistry
     *
     * @mbg.generated
     */
    public Integer getChemistry() {
        return chemistry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill.chemistry
     *
     * @param chemistry the value for skill.chemistry
     *
     * @mbg.generated
     */
    public void setChemistry(Integer chemistry) {
        this.chemistry = chemistry;
    }

    private boolean isBasisRangeSkill(int skill){
        if(skill>70&&skill<0){
            return false;
        }else{
            return true;
        }
    }
}