package com.coc.character.pojo;

import com.coc.character.Util.GJRandom.gjRandoms;

import java.util.Random;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userid
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.str
     *
     * @mbg.generated
     */
    private Integer str;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.agl
     *
     * @mbg.generated
     */
    private Integer agl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.edu
     *
     * @mbg.generated
     */
    private Integer edu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phy
     *
     * @mbg.generated
     */
    private Integer phy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.cha
     *
     * @mbg.generated
     */
    private Integer cha;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.vol
     *
     * @mbg.generated
     */
    private Integer vol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.bod
     *
     * @mbg.generated
     */
    private Integer bod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.bra
     *
     * @mbg.generated
     */
    private Integer bra;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.luck
     *
     * @mbg.generated
     */
    private Integer luck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userid
     *
     * @return the value of user.userid
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userid
     *
     * @param userid the value for user.userid
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.str
     *
     * @return the value of user.str
     *
     * @mbg.generated
     */
    public Integer getStr() {
        return str;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.str
     *
     * @param str the value for user.str
     *
     * @mbg.generated
     */
    public void setStr(Integer str) {
        this.str = str;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.agl
     *
     * @return the value of user.agl
     *
     * @mbg.generated
     */
    public Integer getAgl() {
        return agl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.agl
     *
     * @param agl the value for user.agl
     *
     * @mbg.generated
     */
    public void setAgl(Integer agl) {
        this.agl = agl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.edu
     *
     * @return the value of user.edu
     *
     * @mbg.generated
     */
    public Integer getEdu() {
        return edu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.edu
     *
     * @param edu the value for user.edu
     *
     * @mbg.generated
     */
    public void setEdu(Integer edu) {
        this.edu = edu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phy
     *
     * @return the value of user.phy
     *
     * @mbg.generated
     */
    public Integer getPhy() {
        return phy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phy
     *
     * @param phy the value for user.phy
     *
     * @mbg.generated
     */
    public void setPhy(Integer phy) {
        this.phy = phy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.cha
     *
     * @return the value of user.cha
     *
     * @mbg.generated
     */
    public Integer getCha() {
        return cha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.cha
     *
     * @param cha the value for user.cha
     *
     * @mbg.generated
     */
    public void setCha(Integer cha) {
        this.cha = cha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.vol
     *
     * @return the value of user.vol
     *
     * @mbg.generated
     */
    public Integer getVol() {
        return vol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.vol
     *
     * @param vol the value for user.vol
     *
     * @mbg.generated
     */
    public void setVol(Integer vol) {
        this.vol = vol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.bod
     *
     * @return the value of user.bod
     *
     * @mbg.generated
     */
    public Integer getBod() {
        return bod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.bod
     *
     * @param bod the value for user.bod
     *
     * @mbg.generated
     */
    public void setBod(Integer bod) {
        this.bod = bod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.bra
     *
     * @return the value of user.bra
     *
     * @mbg.generated
     */
    public Integer getBra() {
        return bra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.bra
     *
     * @param bra the value for user.bra
     *
     * @mbg.generated
     */
    public void setBra(Integer bra) {
        this.bra = bra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.luck
     *
     * @return the value of user.luck
     *
     * @mbg.generated
     */
    public Integer getLuck() {
        return luck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.luck
     *
     * @param luck the value for user.luck
     *
     * @mbg.generated
     */
    public void setLuck(Integer luck) {
        this.luck = luck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.age
     *
     * @return the value of user.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.age
     *
     * @param age the value for user.age
     *
     * @mbg.generated
     */
    private String birthplace;
    private  String nationality;

    public String getBirthplace() {
        return birthplace;
    }

    public void setBirthplace(String birthplace) {
        this.birthplace = birthplace;
    }

    public String getNationality() {
        return nationality;
    }

    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    public void setAge(Integer age) {
        this.age = age;
    }
    gjRandoms gj =new gjRandoms();
    Random r = new Random();
    public Integer common(){
        int rxt =r.nextInt(7)+3;
        int rx = 9-gj.doRamdon()+rxt;
        return 5*rx;
    }

    public Integer special(){

        int rxt =r.nextInt(2)+8;
        int rx = 9-gj.doRamdon()+rxt;
        return rx*5;
    }
    public Integer luck(){
        Random r = new Random();
        return r.nextInt(99)+1;
    }
}